# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 615)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(37, 37, 37);\n"
"background-color: #000000;\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 47))
        self.label_11.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(2, 209, 255);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(2, 209, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(2, 209, 255);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;       /* Azul claro */\n"
"    color: white;                    /* Cor do texto */\n"
"    border-radius: 0px;              /* Sem bordas arredondadas */\n"
"    padding: 10px;                   /* Espaçamento interno */\n"
"    font-weight: bold;               /* Texto em negrito */\n"
"   /* border: 2px solid #2980b9;       /* Borda com outra cor */\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c5d7a;       /* Cor ao pressionar o botão */\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;       /* Azul claro */\n"
"    color: white;                    /* Cor do texto */\n"
"    border-radius: 0px;              /* Sem bordas arredondadas */\n"
"    padding: 10px;                   /* Espaçamento interno */\n"
"    font-weight: bold;               /* Texto em negrito */\n"
"   /* border: 2px solid #2980b9;       /* Borda com outra cor */\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c5d7a;       /* Cor ao pressionar o botão */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;       /* Azul claro */\n"
"    color: white;                    /* Cor do texto */\n"
"    border-radius: 0px;              /* Sem bordas arredondadas */\n"
"    padding: 10px;                   /* Espaçamento interno */\n"
"    font-weight: bold;               /* Texto em negrito */\n"
"   /* border: 2px solid #2980b9;       /* Borda com outra cor */\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c5d7a;       /* Cor ao pressionar o botão */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;       /* Azul claro */\n"
"    color: white;                    /* Cor do texto */\n"
"    border-radius: 0px;              /* Sem bordas arredondadas */\n"
"    padding: 10px;                   /* Espaçamento interno */\n"
"    font-weight: bold;               /* Texto em negrito */\n"
"   /* border: 2px solid #2980b9;       /* Borda com outra cor */\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c5d7a;       /* Cor ao pressionar o botão */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;       /* Azul claro */\n"
"    color: white;                    /* Cor do texto */\n"
"    border-radius: 0px;              /* Sem bordas arredondadas */\n"
"    padding: 10px;                   /* Espaçamento interno */\n"
"    font-weight: bold;               /* Texto em negrito */\n"
"   /* border: 2px solid #2980b9;       /* Borda com outra cor */\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c5d7a;       /* Cor ao pressionar o botão */\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setStyleSheet("background-color: rgb(252, 205, 4);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 5px")
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout.addWidget(self.pushButton_16)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setStyleSheet("QStackedWidget {\n"
"    background-color: #ECEFF5;           /* Cor de fundo do QStackedWidget */\n"
"    /*border: 1px solid #dcdcdc;           /* Borda para o QStackedWidget */\n"
"   /* border-radius: 10px;                 /* Bordas arredondadas */\n"
"   /* padding: 10px;                       /* Espaçamento interno */\n"
"}\n"
"QWidget {                                /* Estilo dos widgets dentro do QStackedWidget */\n"
"    background-color: #ECEFF5;   \n"
"background-color:#000000        /* Cor de fundo dos widgets internos */\n"
"    /*background-color: #000000;\n"
"   /* border-radius: 8px;                  /* Bordas arredondadas */\n"
"   /* border: 1px solid #e0e0e0;           /* Borda para os widgets internos */\n"
"      /* padding: 15px;                       /* Espaçamento interno */\n"
"    color: #333333;                      /* Cor do texto */\n"
"    font-size: 14px;                     /* Tamanho da fonte */\n"
"    font-family: \"Arial\", sans-serif;    /* Família da fonte */\n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    color: #4a4a4a;                      /* Cor do texto dos labels */\n"
"    font-size: 16px;                     /* Tamanho da fonte dos labels */\n"
"    font-weight: bold;                   /* Labels em negrito */\n"
"    margin-bottom: 10px;                 /* Espaçamento abaixo dos labels */\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4a90e2;           /* Cor de fundo dos botões */\n"
"    color: white;                        /* Cor do texto dos botões */\n"
"    border: none;                        /* Remove borda padrão dos botões */\n"
"    border-radius: 5px;                  /* Bordas arredondadas dos botões */\n"
"    padding: 8px 15px;                   /* Espaçamento interno dos botões */\n"
"    font-size: 14px;                     /* Tamanho da fonte dos botões */\n"
"    font-weight: bold;                   /* Texto dos botões em negrito */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #357ABD;           /* Cor do botão ao passar o mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #285a8e;           /* Cor do botão ao clicar */\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_Tabela = QtWidgets.QWidget()
        self.pg_Tabela.setObjectName("pg_Tabela")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pg_Tabela)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.pg_Tabela)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.treeWidget.setFont(font)
        self.treeWidget.setStyleSheet("\n"
"background-color: #434142;\n"
"")
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout_4.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.pg_Tabela)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(67, 65, 66);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 1, 0, 1, 1)
        self.DVO = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DVO.setFont(font)
        self.DVO.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.DVO.setObjectName("DVO")
        self.gridLayout_7.addWidget(self.DVO, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_7.addWidget(self.pushButton_9, 3, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_7.addWidget(self.pushButton_10, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 307, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.pg_Tabela)
        self.pg_Logo = QtWidgets.QWidget()
        self.pg_Logo.setObjectName("pg_Logo")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pg_Logo)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.pg_Logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pg_Logo)
        self.pg_CadastroColaborador = QtWidgets.QWidget()
        self.pg_CadastroColaborador.setObjectName("pg_CadastroColaborador")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pg_CadastroColaborador)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_26 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_21 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(200, 0))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(200, 0))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_11.addWidget(self.lineEdit_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(200, 0))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_13.addWidget(self.lineEdit_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.pg_CadastroColaborador)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(200, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.pg_CadastroColaborador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_12.addWidget(self.lineEdit_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_28 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_15.addWidget(self.label_28)
        self.pushButton_15 = QtWidgets.QPushButton(self.pg_CadastroColaborador)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_15.addWidget(self.pushButton_15)
        self.label_27 = QtWidgets.QLabel(self.pg_CadastroColaborador)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_15.addWidget(self.label_27)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.pg_CadastroColaborador)
        self.pg_CadastroUser = QtWidgets.QWidget()
        self.pg_CadastroUser.setObjectName("pg_CadastroUser")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pg_CadastroUser)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(200, 0))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(200, 0))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(200, 0))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_6.addWidget(self.lineEdit_4)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(200, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEdit = QtWidgets.QLineEdit(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.comboBox = QtWidgets.QComboBox(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.pushButton_14 = QtWidgets.QPushButton(self.pg_CadastroUser)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_3.addWidget(self.pushButton_14)
        self.label_18 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_48 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_28.addWidget(self.label_48)
        self.pushButton_20 = QtWidgets.QPushButton(self.pg_CadastroUser)
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_28.addWidget(self.pushButton_20)
        self.label_49 = QtWidgets.QLabel(self.pg_CadastroUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_28.addWidget(self.label_49)
        self.gridLayout_5.addLayout(self.horizontalLayout_28, 7, 0, 1, 1)
        self.stackedWidget.addWidget(self.pg_CadastroUser)
        self.pg_Config = QtWidgets.QWidget()
        self.pg_Config.setObjectName("pg_Config")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pg_Config)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_32 = QtWidgets.QLabel(self.pg_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(0, 0))
        self.label_32.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_18.addWidget(self.label_32)
        self.pushButton_12 = QtWidgets.QPushButton(self.pg_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_18.addWidget(self.pushButton_12)
        self.gridLayout_8.addLayout(self.horizontalLayout_18, 7, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.pg_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 0, 0, 1, 2)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.comboBox_2 = QtWidgets.QComboBox(self.pg_Config)
        self.comboBox_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_17.addWidget(self.comboBox_2)
        self.pushButton_11 = QtWidgets.QPushButton(self.pg_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_17.addWidget(self.pushButton_11)
        self.gridLayout_8.addLayout(self.horizontalLayout_17, 1, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem8, 2, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.pg_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.pushButton = QtWidgets.QPushButton(self.pg_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton {\n"
"     background-color: #434142;       /* Cor ao passar o mouse */\n"
"    color:#FCCD04;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"       /* Cor ao passar o mouse */\n"
"    background-color: rgb(213, 213, 213);\n"
"color:#000000\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d5d5d5;       /* Cor ao pressionar o botão */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_16.addWidget(self.pushButton)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 4, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.pg_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 6, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem9, 5, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.pg_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 3, 0, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem10, 8, 0, 1, 1)
        self.stackedWidget.addWidget(self.pg_Config)
        self.horizontalLayout_9.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">APROVISIONAMENTO DE PEÇAS - </span><span style=\" font-size:14pt; font-weight:600; color:#fccd04;\">REBUILD</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; color:#a4a480;\">Nome:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "NOME"))
        self.label_2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#a4a480;\">Matricula:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "MATRICULA"))
        self.label_12.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; color:#a4a480;\">Função:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "FUNÇÃO"))
        self.pushButton_8.setText(_translate("MainWindow", "Ordem de Serviço"))
        self.pushButton_3.setText(_translate("MainWindow", "Cadastro de colaborador"))
        self.pushButton_2.setText(_translate("MainWindow", "Configurações"))
        self.pushButton_4.setText(_translate("MainWindow", "Cadastrar usuário"))
        self.pushButton_5.setText(_translate("MainWindow", "Sair"))
        self.pushButton_16.setText(_translate("MainWindow", "SOTREQ CAT"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "INDICE"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "ORDEM"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "OPERAÇÃO"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "ITEM"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "PART-NUMBER"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "QUANTIDADE SOLICITADA"))
        self.treeWidget.headerItem().setText(6, _translate("MainWindow", "QUANTIDADE RECEBIDA CDP"))
        self.treeWidget.headerItem().setText(7, _translate("MainWindow", "QUANTIDADE CONFERIDA"))
        self.treeWidget.headerItem().setText(8, _translate("MainWindow", "QUANTIDADE ENTREGUE PARA REFORMA"))
        self.treeWidget.headerItem().setText(9, _translate("MainWindow", "COLABORADOR RESPÓNSAVEL"))
        self.treeWidget.headerItem().setText(10, _translate("MainWindow", "STATUS"))
        self.treeWidget.headerItem().setText(11, _translate("MainWindow", "COMENTÁRIO"))
        self.treeWidget.headerItem().setText(12, _translate("MainWindow", "CONFERÊNTE"))
        self.pushButton_6.setText(_translate("MainWindow", "CONFERÊNCIA"))
        self.pushButton_7.setText(_translate("MainWindow", "ZERAR"))
        self.DVO.setText(_translate("MainWindow", "DVO"))
        self.pushButton_9.setText(_translate("MainWindow", "RETIRADA"))
        self.pushButton_10.setText(_translate("MainWindow", "COMENTÁRIO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#ffffff;\">APROVISIONAMENTO DE PEÇAS</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:36pt; color:#ffc22b;\">REBUILD</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#fccd04;\">CADASTRAR COLABORADOR</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#fccd04;\">NOME:</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#fccd04;\">USUÁRIO:</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#fccd04;\">SENHA:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#fccd04;\">CONFIRMAR SENHA:</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_15.setText(_translate("MainWindow", "CADASTRAR"))
        self.label_27.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#fccd04;\">USUÁRIO:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#fccd04;\">SENHA:</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#fccd04;\">CONFIRMAR SENHA:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#fccd04;\">NOME:</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#fccd04;\">Tipo de Perfil:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Usuário"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Administrador"))
        self.pushButton_14.setText(_translate("MainWindow", "CADASTRAR"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#fccd04;\">CADASTRAR USUÁRIO</span></p></body></html>"))
        self.pushButton_20.setText(_translate("MainWindow", "LIMPAR"))
        self.label_32.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_12.setText(_translate("MainWindow", "Exportar"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#fccd04;\">Selecionar Reforma</span></p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "Selecionar"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Importar"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#fccd04;\">Exportar Banco de Dados</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#fccd04;\">Importar Banco de Dados</span></p></body></html>"))
